Traceback (most recent call last):
  File "/Users/lb788/miniconda3/envs/CfRR/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/lb788/miniconda3/envs/CfRR/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lb788/miniconda3/envs/CfRR/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lb788/miniconda3/envs/CfRR/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/lb788/miniconda3/envs/CfRR/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/lb788/miniconda3/envs/CfRR/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/lb788/miniconda3/envs/CfRR/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from jupyterquiz import display_quiz
display_quiz("../questions/course_skip_quizes/pandas_course_skip_quiz.json")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mjupyterquiz[39;00m [38;5;28;01mimport[39;00m display_quiz
[0;32m----> 2[0m display_quiz([38;5;124m"[39m[38;5;124m../questions/course_skip_quizes/pandas_course_skip_quiz.json[39m[38;5;124m"[39m)

File [0;32m~/miniconda3/envs/CfRR/lib/python3.12/site-packages/jupyterquiz/dynamic.py:176[0m, in [0;36mdisplay_quiz[0;34m(ref, num, shuffle_questions, shuffle_answers, preserve_responses, border_radius, question_alignment, max_width, colors)[0m
[1;32m    173[0m [38;5;28;01melse[39;00m:
[1;32m    174[0m     [38;5;66;03m#print("File detected")[39;00m
[1;32m    175[0m     script [38;5;241m+[39m[38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;124mvar questions[39m[38;5;132;01m{[39;00mdiv_id[38;5;132;01m}[39;00m[38;5;124m=[39m[38;5;124m"[39m
[0;32m--> 176[0m     [38;5;28;01mwith[39;00m [38;5;28mopen[39m(ref) [38;5;28;01mas[39;00m file:
[1;32m    177[0m         [38;5;28;01mfor[39;00m line [38;5;129;01min[39;00m file:
[1;32m    178[0m             script [38;5;241m+[39m[38;5;241m=[39m line

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../questions/course_skip_quizes/pandas_course_skip_quiz.json'

