Traceback (most recent call last):
  File "/Users/lb788/miniconda3/envs/CfRR/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/lb788/miniconda3/envs/CfRR/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lb788/miniconda3/envs/CfRR/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lb788/miniconda3/envs/CfRR/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/lb788/miniconda3/envs/CfRR/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/lb788/miniconda3/envs/CfRR/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/lb788/miniconda3/envs/CfRR/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
##### Exercise 3 Extra 
* What do you think is happening with the filtering code?
* What do you get if you print the output for:
    * air_pollution_data["Year"]
    * air_pollution_data["Year"] == 2022
------------------


[0;36m  Cell [0;32mIn[17], line 3[0;36m[0m
[0;31m    * What do you get if you print the output for:[0m
[0m           ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid syntax


